### ISSUE TITLE
TLV container usage

### ISSUE THREAD

**Issue by accordioff** [karolyi/py3-ecrterm#3]
Dear Karolyi,

the code works really well so far, great job! However, a major improvement would be to utilize the TLV features. They allow further customization of the PT like display size, language, transaction details,....
I haven't managed to get TLV send/receive working. Can you please help?

Cheers

**Comment by karolyi** [comment]
Hey,

@henryk started to implement it which I merged back from time to time, his fork seems to have disappeared meanwhile though. If you look into the https://github.com/karolyi/py3-ecrterm/tree/py3 branch, there are the commits. I have never tested it though, it was a work in progress as far as I know.

Feel free to use and review that, pull requests/fixes are welcome, but mind you I offer no warranties to that branch as it is now. If and when we can get a more or less stable version of it, merging back to master (and a release) can become an option.

**Comment by henryk** [comment]
Yes, I'm currently using https://github.com/henryk/ecrterm/tree/py3 in an on-going project, in production. There will be some more changes in December/January as we prepare a new product, at which point I intend to prepare the code to be able to merge back.
The functionality of my fork is greatly enhanced, but beware: most of the internal API is changed and made more sane. Some problems remain (and I'll probably need to break some API come January).

**Comment by accordioff** [comment]
@karolyi : Thank you, thats the hot stuff!

@henryk : Oh yeah, the "tlv.py" saw a lot of your love! Great work!
How can I step in to contribute? Maybe the boring stuff like TAG-names similar to the "bitmap.py"?
Honestly, my programming skills are mediocre at best - so I don't dare to offer thouse... :-/

**Comment by accordioff** [comment]
Had a dive into @henryk solution. It looks very promissing. I was able to utilise the TLV containers. I'm looking forward to the upcomming merges.
